[package]
name = "twitter-images"
version = "0.2.0"
edition = "2021"
authors = ["Harsh Shandilya <me@msfjarvis.dev>"]
license = "MIT/Apache-2.0"
description = "Fetch original quality images from the tweets of a given Twitter user"
repository = "https://github.com/msfjarvis/twitter-images"
homepage = "https://github.com/msfjarvis/twitter-images"
keywords = ["twitter", "images"]
readme = "README.md"
publish = false
include = ["src/main.rs", "LICENSE-*", "README.md"]

[dependencies]
clap = { version = "3.2.15", features = [ "color", "deprecated", "derive", "env" ] }
color-eyre = { version = "0.6.2", default-features = false }
egg-mode = { version = "0.16.0", features = ["rustls_webpki"], default-features = false }
mime = "0.3"
mime_guess = "2.0.4"
tokio = { version = "1.20.1", features = ["rt-multi-thread", "macros"] }
url = "2.2.2"
