allow-branch = ["main"]
push = true
pre-release-commit-message = "chore(release): bump {{crate_name}} to version {{version}}"
tag-message = "{{crate_name}} version {{version}}"
tag-name = "v{{version}}"
